### ISSUE TITLE
logit_cubic_climate_parameter function

### ISSUE THREAD

**Issue by SteveViss** [QUICC-FOR/STModel-Simulation#16]
``` C
static inline double logit_cubic_climate_parameter(Climate * cl, double * pars)
{
    double result = pars[0] + pars[1]*cl->env1 + pars[2]*cl->env2 + 
            pars[3]*pow(cl->env1,2) + pars[4]*pow(cl->env2,2) + pars[5]*pow(cl->env1,3) + 
            pars[6]*pow(cl->env2,3);
    return result;
}
```

In the case pars[5] and pars[6] are missing from the input file parameters (quadratic polynomial). pars[5] and pars[6] are initialized on 0 by default ? I looked the function parse_input_parameter (line 206, src/climate.c) but I didn't get my answer.

**Comment by mtalluto** [comment]
Please refer to the function `cg_initialize_parameters`.

In particular, the following code block initializes all of the climate microparameters to zero:

````C
for(int i = 1; i < CL_NUM_TERMS; i++) {
    pars->alphaB[i] = pars->alphaT[i] = pars->betaB[i] = pars->betaT[i] = 0;
    pars->theta[i] = pars->thetaT[i] = pars->epsi[i] = 0;
}
````

**Comment by SteveViss** [comment]
I missed it ! Thanks !
